### ISSUE TITLE
Corregir el 8_prog_dec_bin.c

### ISSUE THREAD

**Issue by pacificosur** [william120597/20_ProyectosEstructurada#5]
# Si se tomó este programa de alguna fuente, por favor debe incluir esa fuente.

Nosotros no hemos visto funciones, y en este código está incluyendo funciones, es bueno que este tipo de código, pero lo importante es que desarrolle sus propios programas.

Saludos

**Comment by william120597** [comment]
cierto profe  no se lo voy a negar la verdad es que me estaba costando trabajo y pues vi un video en donde  lo realizaban mediante funciones y pues lo tome de ahi pero no se preocupe intentare hacerlo mediante otro método.
